### PR TITLE
Added private function __search_expand_command_path()

### PR DESCRIPTION
**Pull request by alfkil**
Work-in-progress suggestion for an added cli path search for the unix-amiga path translation utility functions.

### CODE REVIEW

**Review by afxgroup — CHANGES_REQUESTED** [review]
Please:

1. Remove changes from GNUMakefile.os4
2. Use `__USE_INLINE__` in **search_command_path.c** file since all library (except for shared library initalization) is not using interfaces
3. in **translateu2a.c** remove commented function and please reformat code to follow the code 
4. in **unistd_headers.h** there is now an `extern struct UtilityIFace *__IUtility` that is not needed

**Comment by alfkil** [comment]
How do I access IUtility, if I can not refer to __IUtility?
Do I have privileges to call OpenLibrary()/GetInterface()? Or is there a different solution?

**Comment by afxgroup** [comment]
Add:

`DECLARE_UTILITYBASE();`

In your code. Search for `DECLARE_UTILITYBASE();` to see how it is used

**Comment by alfkil** [comment]
@afxgroup : 3. In translateu2a.c remove commented function and please reformat code to follow the code

I am guessing, you mean the call to __translate_relative_path_name...?

I think, it should still be there, since it could still be relevant *after* a cmd path search. What do you think?

**Comment by afxgroup** [comment]
I'm speaking about code writing convention. Meaning formatting code. for example if(a) is wrong. If (a) is correct. LiteXl should have a formatter

**Comment by alfkil** [comment]
I added formatter_clangformat.lua to the lite-xl plugins. The plugin is activated on keycombo (it writes a message), but the command does nothing. From looking at the lua, it seems, that it is not really implemented. I guess that is another vacation project.

**Pull request merged**
